### ISSUE TITLE
Create the missing Documents and Update the outdated ones.

### ISSUE THREAD

**Issue by Mohit-3196** [ant-media/Ant-Media-Server#4841]
- [ ] Sample documentation for localVideoElement and remoteVideoElement
 #4553 
- [ ] Virtual Background Support
- [ ] Zixi Integration with AMS (There is a blogpost)
- [ ] Multiuser capability for TOTP Subscriber - Update stream security document
- [ ] Free Domain and SSL support - Update setting up SSL document
- [ ] Android SDK - Outdated
- [ ] iOS SDK - Add Screen sharing and other new features like multitrack conference, etc.
- [ ] TURN Server (Current document needs refactoring about TURN configuration on the server side and client side)
- [ ] HLS Load Test
- [ ] Setting up Kubernetes cluster for Google Cloud

**Comment by mekya** [comment]
Hey @Mohit-3196 ,

Thank you for your work. Could you please add these items to this issue?
https://github.com/ant-media/Ant-Media-Server/issues/4526

So that there will be no duplication

**Comment by Mohit-3196** [comment]
Hello @mekya abi,
It is done.

Thank you

**Comment by mekya** [comment]
Thank you

**Comment by mekya** [comment]
I'm just closing this issue then.
