### ISSUE TITLE
Tunadesk problem reported by user

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#5370]
- [x] [The mouse wheel scrolls the content in the opposite direction of the movement of the wheel](https://github.com/ant-media/TunaDesk/issues/10)
- [x] [Resolution changes in the real machine, is not synchronized with remote tunadesk viewer](https://github.com/ant-media/TunaDesk/issues/15)
- [x] [Right click opens on host machine and controller machine and causes confusion](https://github.com/ant-media/TunaDesk/issues/13)
- [ ] [Cursor "freezes" while trying to minimize tunadesk control interface. Have to move the mouse in the host in order for the mouse to move again](https://github.com/ant-media/TunaDesk/issues/5)
- [x] [Mouse pointer has a second pointer that "chases" the first one and it has a severe delay synchronizing between them](https://github.com/ant-media/TunaDesk/issues/4)
- [ ] [Slow performance of the remote desktop control](https://github.com/ant-media/TunaDesk/issues/16)

**Comment by mustafaboleken** [comment]
We just completed the tasks, it's time to close this one.
